name: Daily attendance sheet

on:
  schedule:
    # 06:30 UTC every day -> 12:00 IST
    - cron: '30 06 * * *'
  workflow_dispatch: {}  # allow manual runs

jobs:
  create-attendance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run createAttendance script
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SA_JSON }}
          DEPT: ECA
          TZ: Asia/Kolkata
          SIGNED_URL_EXPIRE_DAYS: '7'
        run: node createAttendance.js
